[[redirects]]
  from = "/sitemap.xml"
  to = "https://tpthlopfhyuuspgooblk.supabase.co/functions/v1/sitemap?type=index"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap-blog.xml"
  to = "https://tpthlopfhyuuspgooblk.supabase.co/functions/v1/sitemap?type=blog"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap-static.xml"
  to = "https://tpthlopfhyuuspgooblk.supabase.co/functions/v1/sitemap?type=static"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap-categories.xml"
  to = "https://tpthlopfhyuuspgooblk.supabase.co/functions/v1/sitemap?type=categories"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap-events.xml"
  to = "https://tpthlopfhyuuspgooblk.supabase.co/functions/v1/sitemap?type=events"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap-banners.xml"
  to = "https://tpthlopfhyuuspgooblk.supabase.co/functions/v1/sitemap?type=banners"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap-markets.xml"
  to = "https://tpthlopfhyuuspgooblk.supabase.co/functions/v1/sitemap?type=markets"
  status = 200
  force = true


[[redirects]]
  from = "/sitemap-campaigns.xml"
  to = "https://tpthlopfhyuuspgooblk.supabase.co/functions/v1/sitemap?type=banners"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap-business.xml"
  to = "https://tpthlopfhyuuspgooblk.supabase.co/functions/v1/sitemap?type=business"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap-parties.xml"
  to = "https://tpthlopfhyuuspgooblk.supabase.co/functions/v1/sitemap?type=parties"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap-listings.xml"
  to = "https://tpthlopfhyuuspgooblk.supabase.co/functions/v1/sitemap?type=index"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap-listings-index.xml"
  to = "https://tpthlopfhyuuspgooblk.supabase.co/functions/v1/sitemap?type=listings-index"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap-listings-:category.xml"
  to = "https://tpthlopfhyuuspgooblk.supabase.co/functions/v1/sitemap?type=listings-category&category=:category"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap-digital.xml"
  to = "https://tpthlopfhyuuspgooblk.supabase.co/functions/v1/sitemap?type=digital"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap-elections.xml"
  to = "https://tpthlopfhyuuspgooblk.supabase.co/functions/v1/sitemap?type=elections"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
